analyze_inventory_task:
  description: >
    Analyze the uploaded fridge photo or manual input to detect and normalize the current available ingredients.
  expected_output: >
    A clean, structured list of available ingredients.
  agent: inventory_analyzer

filter_preferences_task:
  description: >
    Filter the list of ingredients and meals based on the user's dietary preferences, allergies, and disliked ingredients.
  expected_output: >
    A refined list of ingredients and potential meals that comply with the user's preferences.
  agent: preference_filter

generate_dishes_task:
  description: >
    Using the filtered ingredients and preferences, generate 3-5 diverse, simple dishes including title, prep time, description, and ingredients used.
  expected_output: >
    A list of 3-5 structured dish suggestions in JSON format with name, ingredients used, estimated cooking time, and description.
  agent: dish_generator

plan_meals_task:
  description: >
    Distribute the suggested meals into a 7-day meal calendar, ensuring variety and nutrition balance.
  expected_output: >
    A weekly plan mapping each dish to a specific day and meal time (breakfast/lunch/dinner).
  agent: meal_planner

identify_grocery_gaps_task:
  description: >
    Compare the user's grocery history and current fridge contents with the weekly meal plan to generate a shopping list of missing items.
  expected_output: >
    A smart grocery list grouped by category (e.g., Produce, Dairy) showing what needs to be bought for the week.
  agent: grocery_gap_identifier
